[package]
name = "cargo_crev_web"
#no need for semver if it is not a library
version = "2020.501.1211" 
description = "web server to query reviews from cargo-crev"
authors = ["Luciano Bestia"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/lucianobestia/cargo_crev_web"
categories = ["web-programming"]
keywords = ["warp","crev","cargo-crev"]
publish = false

[dependencies]
futures = "0.3.4"
log = "0.4.8"
env_logger = "0.7.1"
warp="0.2.2"
regex="1.3.7"
tokio = { version = "0.2", features = ["macros"] }
# cmd line input parameters
clap ="2.33.0"
# colorful output to screen
ansi_term = "0.12.1"
serde = "1.0.106"
serde_derive ="1.0.106"
serde_yaml = "0.8.11"
unwrap = "1.2.1"
# regex = "1.3.6"
# lazy_static="1.4.0"
glob="0.3.0"
dirs="2.0.2"
